changelog:
  exclude:
    authors:
      - rbs-bot
  categories:
    - title: ⚠️ Breaking Changes
      labels:
        - major-update
        - breaking-change
    - title: ⭐ New Features
      labels:
        - "*"
        - "feature"
    - title: 🐞 Bug Fixes
      labels:
        - bugfix
    - title: 📦 Dependency Upgrades
      labels:
        - dependencies
    - title: 📔 Documentation
      labels:
        - documentation
    - title: ⚙️ Miscellaneous
      labels:
        - miscellaneous
