name: 'Build'

on:
  pull_request:
    branches: 
      - main
  push: 
    branches:
      - main

jobs:
  build:
    permissions:
      contents: read
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #6.0.2
      - name: Setup Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - uses: pnpm/action-setup@078e9d416474b29c0c387560859308974f7e9c53
        name: Install pnpm
        with:
            version: 9
            run_install: false
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e #6.4.0
        name: Install Node.js
        with:
            node-version: 24
            cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm run build
      - name: Archive production artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a #7.0.1
        with:
          name: expander-card
          path: |
              dist
