name: Validate

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  validate-hacs:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #6.0.2
      - name: HACS validation
        uses: hacs/action@d556e736723344f83838d08488c983a15381059a
        with:
          category: "plugin"
