name: Validate

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  validate-hacs:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 #6.0.3
      - name: HACS validation
        uses: hacs/action@d556e736723344f83838d08488c983a15381059a
        with:
          category: "plugin"
